
name: "dbt-demo-wf"

config-version: 2
version: '0.1'

profile: 'prophecy-bigquery'

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models: {}
